name: Alghawali Apis Deploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/alghawali/alghawali/training/training-apis
          git remote set-url origin git@github.com:umarrfarooooq/alghawali-apis.git
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          git pull origin master
          npm install
          pm2 restart app.js
