name: Alghawali APIs Deploy

on:
  push:
    branches:
      - master
      - training

jobs:
  deploy_training_apis:
    if: github.ref == 'refs/heads/training' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Training APIs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/alghawali/alghawali/training/apis
            git remote set-url origin git@github.com:umarrfarooooq/training-apis.git
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            npm install
            pm2 restart app.js

  deploy_alghawali_apis:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Alghawali APIs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/alghawali/alghawali/alghawali-apis/alghawali-apis
            git remote set-url origin git@github.com:umarrfarooooq/alghawali-apis.git
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            git pull
            npm install
            pm2 restart app.js